# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## !USE TEXT THEME
theme: jekyll-text-theme
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

text_color_theme: dark #eg: default | dark | forest | ocean | chocolate | orange
## Base settings ##
url: http://blog.minzhou.info  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: About Distributed
description: > #this means to ignore newlines until "nav_lists:"
  About Distributed.

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

# paths:
#   base: /
#   home: /
#   all:  /all.html
#   rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository:  coderplay/coderplay.github.com #e.g. someone/someone.github.io
repository_tree: master #e.g. master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: America/Los_Angeles #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: Min Zhou
  email: coderplay@gmail.com  #your Email address e.g. someone@site.com
  # facebook:  #your Facebook username
  twitter: minzhou #your Twitter username
  github: coderplay  #your GitHub username
  # googleplus:  #your Google+ username
  weibo: coderplay #your Weibo username
  # douban:  #your Douban username
  linkedin: coderplay  #your Linkedin username

## TOC
toc:
  # selectors: 'h1,h2,h3'

## Comment system (Disqus) ##
disqus:
  # shortname: minzhou
  # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: 48d6cd77365935ec481e #Github Application Client ID
  ClientSecret: 5402c2d7a1f032b2504c65ea4c20c52ab65c46ce  #Github Application Client Secret
  Repository:  coderplay.github.io  #Github repo
  owner: coderplay #Github repo owner
  admin:  #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - coderplay
    # - owner

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

mathjax: true
mathjax_autoNumber: true
mermaid: true
chart: true

## Paginate ##
paginate: 7
paginate_path: /page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Sources ##
# sources: bootcss #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"
